[package]
name = "nvisual"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.1.1"
futures = "0.3.31"
threadpool = "1.8.1"
tokio = { version = "1.48.0", features = ["full"] }
